name: Build DeskQTA

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Arch Linux container (Linux only)
        if: matrix.os == 'ubuntu-22.04'
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel webkit2gtk gtk3 libsoup libappindicator-gtk3
            # Install Node.js, Rust, and build as normal
            curl -fsSL https://fnm.vercel.app/install | bash
            export PATH=$HOME/.fnm:$PATH
            eval "$(fnm env)"
            fnm install 20
            fnm use 20
            npm install -g @tauri-apps/cli
            npm install
            npm run tauri build

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        run: npm install

      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            pkg-config \
            libsoup-3.0-dev \
            libappindicator3-dev \
            patchelf

      - name: Build app
        run: npm run tauri build 